### PR TITLE
Use "w+" mode for opening/creating the unoconv lock file

### PR DESCRIPTION
**Pull request by jensschuppe**
If I understand correctly, attempting a file lock for the *unoconv* lock file should create it if it doesn't exist. However, `fopen()` uses `r+` which doesn't create the file if it's missing.

*systopia-reference: 23962*

### CODE REVIEW

**Comment by jensschuppe** [comment]
Well, `r+` is for reading *and* writing, just as `w+` while the latter also truncates the file. I'm not sure that's what we want, but `w` and `w+` creates the file if it doesn't exist, while `r+` does not do that, which is the actual problem here …

**Comment by bjendres** [comment]
I don't see any harm in the change, provided it was successfully tested on a local and on the typical client's setup.

**Review by dontub — APPROVED** [review]

**Comment by jensschuppe** [comment]
> provided it was successfully tested on […] the typical client's setup.

Not yet, so this will have to wait …

**Comment by jensschuppe** [comment]
This has been tested by @svenow on another environment, so this is ready to merge now.

**Pull request merged**
